h8r-dev/heighliner

- pkg/version/version.go
Signed-off-by: wangwei <434533508@qq.com>
> feat: upgrade dagger

- docs/gen.go
> fix: quote Figlet in docs

- cmd/hln/cmd/up.go
> fix: check input value format

- cmd/hln/cmd/logs.go
- pkg/state/app/output.go
- pkg/state/configmap_state.go
> fix: applicationRef in output and logs

- cmd/hln/cmd/down.go
- go.mod
- go.sum
`hln down [appName] --delete-packages`
> feat: supports delete packages

- pkg/stack/stack.go
> feat: add spring-vue

- pkg/version/version.go
Signed-off-by: wangwei <434533508@qq.com>
> feat: upgrade dagger v0.2.10

- cmd/hln/cmd/up.go
> fix: update upcmd usage desc

- cmd/hln/cmd/down.go
- cmd/hln/cmd/list.go
- cmd/hln/cmd/list_stacks.go
> fix: remove description in list stacks

- cmd/hln/cmd/down.go
- cmd/hln/cmd/logs.go
- cmd/hln/cmd/root.go
- cmd/hln/cmd/status.go
- internal/k8sfactory/factory.go
- pkg/util/k8sutil/k8sutil.go
> refactor: move get k8s client methods to internal

- cmd/hln/cmd/down.go
- cmd/hln/cmd/up.go
- cmd/hln/cmd/variables.go
> fix: remove .hln dir bug

- cmd/hln/cmd/metrics.go
> fix: decode and unmarshal bug

- cmd/hln/cmd/get.go
- cmd/hln/cmd/get_ingress.go
- cmd/hln/cmd/root.go
- cmd/hln/cmd/up.go
> feat: get ingress ip

- cmd/hln/cmd/metrics.go
> fix: metrics url bug

- cmd/hln/cmd/down.go
> feat: down cmd needs confirmation

- cmd/hln/cmd/list_stacks.go
- go.mod
- pkg/stack/stack.go
> fix: remove hardcoded stacks

- cmd/hln/cmd/init.go
Signed-off-by: wangwei <434533508@qq.com>
> feat: increase FailureThreshold

- cmd/hln/cmd/up.go
- go.mod
- pkg/stack/stack.go
> feat: support specify version

- cmd/hln/cmd/status.go
> bugfix: fix status output, support parse multi items in prompt field

- go.mod
- pkg/schema/schema.go
- pkg/state/app/output.go
- pkg/state/configmap_state.go
- pkg/state/local_file_state.go
https://github.com/go-yaml/yaml/issues/666
> fix: use yaml.v2

- go.mod
- pkg/schema/schema.go
- pkg/state/app/output.go
- pkg/state/configmap_state.go
- pkg/state/local_file_state.go
> fix: use k8s yaml pkg

- cmd/hln/cmd/metrics.go
> fix: support multi dashboards

- cmd/hln/cmd/down.go
- pkg/state/configmap_state.go
- pkg/state/interface.go
- pkg/state/local_file_state.go
> fix: down failed to delete configmap bug

- cmd/hln/cmd/init.go
- cmd/hln/cmd/up.go
Reverts h8r-dev/heighliner#221
> Revert "fix: move install buildkit to up cmd"

- cmd/hln/cmd/list.go
- cmd/hln/cmd/list_apps.go
- cmd/hln/cmd/list_stacks.go
- cmd/hln/cmd/logs.go
- cmd/hln/cmd/metrics.go
- cmd/hln/cmd/root.go
- cmd/hln/cmd/status.go
- cmd/hln/cmd/up.go
- cmd/hln/cmd/version.go
> fix: redirect iostreams

- pkg/dagger/action.go
> fix: validate stack dir

- cmd/hln/cmd/init.go
> fix: set KUBECONFIG env for infra installation

- cmd/hln/cmd/up.go
> fix: remove output printing

- cmd/hln/cmd/init.go
- pkg/state/configmap_state.go
- pkg/state/const.go
- pkg/state/infra/infra.go
- pkg/state/interface.go
- pkg/state/local_file_state.go
Signed-off-by: Jinming Guo <vgjm456@qq.com>
> feat: print dashboard url after initialization

- cmd/hln/cmd/up.go
Signed-off-by: vgjm <vgjm@foxmail.com>
> feat: remove appName parameter for up cmd
